apiVersion: apps/v1
kind: Deployment
metadata:
  name: microbot
spec:
  replicas: 2 # จำนวน replica สำหรับ Dev
#  template:
#    spec:
#      containers:
#      - name: microbot
#        image: naiin9/microbot:v1 # Image tag สำหรับ Dev
---
apiVersion: v1
kind: Service
metadata:
  name: microbot-svc
spec:
  type: NodePort
  selector:
    app: microbot
  ports:
  - nodePort: 31213