apiVersion: apps/v1
kind: Deployment
metadata:
  name: microbot2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: microbot2
  template:
    metadata:
      labels:
        app: microbot2
    spec:
      containers:
      - name: microbot
        image: naiin9/microbot:v1
        ports:
        - containerPort: 80
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: MY_NODE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        imagePullPolicy: Always
